name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Check System
        run: |
          which brew || echo "brew not found"
          which git || echo "git not found"

      - name: Setup Homebrew & Various Tools
        run: |
          #/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install git ccache autoconf libtool automake pkg-config sassc optipng python bison flex

      - name: Setup JHbuild
        run: |
          ln -sf $PWD/osx/jhbuildrc-custom $HOME/.jhbuildrc-custom
          /bin/bash -c "$(curl -fsSL https://gitlab.gnome.org/GNOME/gtk-osx/raw/master/gtk-osx-setup.sh)"

      - name: Build Environment
        run: |
          cd osx && /bin/bash ./build_env.sh

      
